# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from untitled_project.server.models.base_model_ import Model
from untitled_project.server.models.document import Document  # noqa: F401,E501
from untitled_project.server import util


class ArrayOfDocuments(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """ArrayOfDocuments - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ArrayOfDocuments':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ArrayOfDocuments of this ArrayOfDocuments.  # noqa: E501
        :rtype: ArrayOfDocuments
        """
        return util.deserialize_model(dikt, cls)
